/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivacyPolicyIndexImport } from './routes/privacy-policy/index'
import { Route as PedigreeIndexImport } from './routes/pedigree/index'
import { Route as AnimalsIndexImport } from './routes/animals/index'
import { Route as AnimalsAnimalIdIndexImport } from './routes/animals/$animalId/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const BreedingIndexLazyImport = createFileRoute('/breeding/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const BreedingIndexLazyRoute = BreedingIndexLazyImport.update({
  path: '/breeding/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/breeding/index.lazy').then((d) => d.Route),
)

const PrivacyPolicyIndexRoute = PrivacyPolicyIndexImport.update({
  path: '/privacy-policy/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/privacy-policy/index.lazy').then((d) => d.Route),
)

const PedigreeIndexRoute = PedigreeIndexImport.update({
  path: '/pedigree/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/pedigree/index.lazy').then((d) => d.Route),
)

const AnimalsIndexRoute = AnimalsIndexImport.update({
  path: '/animals/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/animals/index.lazy').then((d) => d.Route))

const AnimalsAnimalIdIndexRoute = AnimalsAnimalIdIndexImport.update({
  path: '/animals/$animalId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/animals/$animalId/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/animals/': {
      id: '/animals/'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AnimalsIndexImport
      parentRoute: typeof rootRoute
    }
    '/pedigree/': {
      id: '/pedigree/'
      path: '/pedigree'
      fullPath: '/pedigree'
      preLoaderRoute: typeof PedigreeIndexImport
      parentRoute: typeof rootRoute
    }
    '/privacy-policy/': {
      id: '/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyIndexImport
      parentRoute: typeof rootRoute
    }
    '/breeding/': {
      id: '/breeding/'
      path: '/breeding'
      fullPath: '/breeding'
      preLoaderRoute: typeof BreedingIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/animals/$animalId/': {
      id: '/animals/$animalId/'
      path: '/animals/$animalId'
      fullPath: '/animals/$animalId'
      preLoaderRoute: typeof AnimalsAnimalIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/animals': typeof AnimalsIndexRoute
  '/pedigree': typeof PedigreeIndexRoute
  '/privacy-policy': typeof PrivacyPolicyIndexRoute
  '/breeding': typeof BreedingIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/animals/$animalId': typeof AnimalsAnimalIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/animals': typeof AnimalsIndexRoute
  '/pedigree': typeof PedigreeIndexRoute
  '/privacy-policy': typeof PrivacyPolicyIndexRoute
  '/breeding': typeof BreedingIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/animals/$animalId': typeof AnimalsAnimalIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/animals/': typeof AnimalsIndexRoute
  '/pedigree/': typeof PedigreeIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/breeding/': typeof BreedingIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/animals/$animalId/': typeof AnimalsAnimalIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animals'
    | '/pedigree'
    | '/privacy-policy'
    | '/breeding'
    | '/login'
    | '/animals/$animalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animals'
    | '/pedigree'
    | '/privacy-policy'
    | '/breeding'
    | '/login'
    | '/animals/$animalId'
  id:
    | '__root__'
    | '/'
    | '/animals/'
    | '/pedigree/'
    | '/privacy-policy/'
    | '/breeding/'
    | '/login/'
    | '/animals/$animalId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AnimalsIndexRoute: typeof AnimalsIndexRoute
  PedigreeIndexRoute: typeof PedigreeIndexRoute
  PrivacyPolicyIndexRoute: typeof PrivacyPolicyIndexRoute
  BreedingIndexLazyRoute: typeof BreedingIndexLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  AnimalsAnimalIdIndexRoute: typeof AnimalsAnimalIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AnimalsIndexRoute: AnimalsIndexRoute,
  PedigreeIndexRoute: PedigreeIndexRoute,
  PrivacyPolicyIndexRoute: PrivacyPolicyIndexRoute,
  BreedingIndexLazyRoute: BreedingIndexLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  AnimalsAnimalIdIndexRoute: AnimalsAnimalIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/animals/",
        "/pedigree/",
        "/privacy-policy/",
        "/breeding/",
        "/login/",
        "/animals/$animalId/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/animals/": {
      "filePath": "animals/index.tsx"
    },
    "/pedigree/": {
      "filePath": "pedigree/index.tsx"
    },
    "/privacy-policy/": {
      "filePath": "privacy-policy/index.tsx"
    },
    "/breeding/": {
      "filePath": "breeding/index.lazy.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/animals/$animalId/": {
      "filePath": "animals/$animalId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
